# Generated by Django 5.0.6 on 2024-06-25 20:03

import Main.untils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_tag_alter_genre_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа')),
                ('year', models.IntegerField(verbose_name='Год основания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ready', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Публикация')),
                ('photo', models.ImageField(upload_to=Main.untils.band_directory_path, verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='Слаг')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genre_status', to='Main.genre', verbose_name='Жанр')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_status', to='Main.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
            bases=(Main.untils.ModelMixinData, models.Model),
        ),
    ]
