# Generated by Django 5.0.6 on 2024-06-29 08:42

import Main.untils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_album_options_alter_album_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.FileField(upload_to=Main.untils.track_directory_path, verbose_name='Путь')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_status', to='Main.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['album'],
            },
        ),
    ]
